general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
}

# FONDO DE PANTALLA (Con Blur)
background {
    monitor =
    path = /home/mike/Pictures/wallpapers/fondo54.png
}

# CAJA DE TEXTO (Contraseña)
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true

    # Tu color #732322 con 80% de opacidad (0.8)
    outer_color = rgba(115, 35, 34, 0.8) 
    
    # Fondo muy sutil para que resalte el borde
    inner_color = rgba(30, 30, 46, 0.2)
    
    font_color = rgb(205, 214, 244)
    fade_on_empty = true
    hide_input = false
    position = 0, -20
    halign = center
    valign = center
}

# HORA GIGANTE
label {
    monitor =
    text = $TIME
    color = rgb(205, 214, 244)
    font_size = 64
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 80
    halign = center
    valign = center
}

# FECHA
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B %Y")"
    color = rgb(205, 214, 244)
    font_size = 22
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 160
    halign = center
    valign = center
}
