enabled_layouts splits
# Opacidad del fondo (0.0 a 1.0)
# 0.8 es un buen equilibrio. 1.0 es sólido, 0 es invisible.
background_opacity 0.8

# Colores dinámicos (opcional, para que se vea mejor)
dynamic_background_opacity yes

font_size 16.0


# BEGIN_KITTY_THEME
# Gruvbox Material Dark Hard
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# BINDS
map ctrl+shift+i launch --location=vsplit --cwd=current
map ctrl+shift+- launch --location=hsplit --cwd=current
map ctrl+w close_window

# Navegar entre ventanas con estilo Vim
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down
