#!/bin/bash
sleep 1
# Matar instancias previas para limpiar el entorno
killall -e xdg-desktop-portal-hyprland
killall -e xdg-desktop-portal-wlr
killall xdg-desktop-portal
killall -e xdg-desktop-portal-gtk

# Iniciar los portales en orden correcto
/usr/lib/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib/xdg-desktop-portal &
sleep 1
/usr/lib/xdg-desktop-portal-gtk &
